import { describe, expect, it } from 'vitest';
import type { MatchRecord, Principal } from '../src/domain.js';
import { MatchRuntime } from '../src/matchRuntime.js';
import { MemoryRepository } from '../src/memoryRepository.js';
import { createSeededRng } from '../src/rng.js';
import { QueueService, RoomService, ServiceError } from '../src/services.js';

const guest=(id:string):Principal=>({id,accountId:null,username:null,guest:true});
const account=(id:string):Principal=>({id,accountId:id,username:id,guest:false});
const match=(mode:'casual'|'ranked'|'room'='casual'):MatchRecord=>({id:`match-${mode}`,mode,status:'playing',seed:'fixed-seed',rulesVersion:'cs-push-v1',participants:[{principal:account('a'),side:'ct'},{principal:account('b'),side:'t'}]});
class FakeClock { time=0; callback:(()=>void)|null=null;now=()=>this.time;setInterval=(callback:()=>void,_ms:number)=>{this.callback=callback;return 1 as unknown as ReturnType<typeof setInterval>;};clearInterval=()=>{this.callback=null;};advance(ms:number){this.time+=ms;}fire(){this.callback?.();} }

const rejection=async(promise:Promise<unknown>,code:string)=>{await expect(promise).rejects.toMatchObject({code});};

describe('seeded RNG and runtime',()=>{
  it('produces deterministic seeded sequences and snapshots',async()=>{const a=createSeededRng('same'),b=createSeededRng('same');expect(Array.from({length:20},()=>a.next())).toEqual(Array.from({length:20},()=>b.next()));const repo1=new MemoryRepository(),repo2=new MemoryRepository();const r1=new MatchRuntime(match(),repo1),r2=new MatchRuntime(match(),repo2);r1.connect('a');r1.connect('b');r2.connect('a');r2.connect('b');for(let i=0;i<10;i+=1){await r1.tick();await r2.tick();}expect(r1.snapshot()).toEqual(r2.snapshot());});
  it('rejects illegal commands and makes commandId idempotent',async()=>{const repo=new MemoryRepository(),clock=new FakeClock(),runtime=new MatchRuntime(match(),repo,clock);runtime.connect('a');await rejection(runtime.command(account('a'),'bad',{type:'buy_deploy',slot:99,lane:0}),'INVALID_SLOT');const first=await runtime.command(account('a'),'forfeit-1',{type:'forfeit'});const again=await runtime.command(account('a'),'forfeit-1',{type:'forfeit'});expect(first).toEqual({sequence:1,duplicate:false});expect(again).toEqual({sequence:1,duplicate:true});});
  it('advances at 10Hz with explicit start and stop',async()=>{const repo=new MemoryRepository(),clock=new FakeClock(),runtime=new MatchRuntime(match(),repo,clock);runtime.connect('a');runtime.connect('b');runtime.start();expect(clock.callback).not.toBeNull();clock.fire();await Promise.resolve();expect(runtime.snapshot().state.elapsed).toBeCloseTo(.1);runtime.stop();expect(clock.callback).toBeNull();});
  it('uses AI while disconnected then forfeits after 30 seconds',async()=>{const repo=new MemoryRepository(),clock=new FakeClock(),record=match();await repo.saveMatch(record);const runtime=new MatchRuntime(record,repo,clock);runtime.connect('a');runtime.connect('b');runtime.disconnect('a');for(let i=0;i<20;i+=1)await runtime.tick();expect(runtime.snapshot().state.elapsed).toBeCloseTo(2);clock.advance(30_000);await runtime.tick();expect((await repo.getMatch(record.id))?.result).toMatchObject({outcome:'t',reason:'disconnect'});});
});

describe('queue and rooms',()=>{
  it('cleans stale activity before allowing a new queue entry',async()=>{const repo=new MemoryRepository(),queues=new QueueService(repo);await repo.claimActivity({principalId:'a',kind:'match',referenceId:'missing-match'});await queues.join(account('a'),'casual');expect(await repo.getActivity('a')).toMatchObject({kind:'queue'});});
  it('rejects ranked guests and enforces one active activity',async()=>{const repo=new MemoryRepository(),queues=new QueueService(repo);await rejection(queues.join(guest('g'),'ranked'),'REGISTERED_REQUIRED');await queues.join(account('a'),'casual');await rejection(new RoomService(repo).create(account('a')),'ACTIVE_ACTIVITY');});
  it('cleans a stale queue activity after the queue row is gone',async()=>{const repo=new MemoryRepository(),queues=new QueueService(repo);const entry=await queues.join(account('a'),'casual');await repo.deleteQueue('a');expect(await queues.current('a')).toEqual({status:'idle'});const room=await new RoomService(repo).create(account('a'));expect(room.members[0].principal.id).toBe('a');});
  it('expands ranked matching range by 50 every 10 seconds',async()=>{let now=new Date(0);const repo=new MemoryRepository(),queues=new QueueService(repo,()=>now);const entry=await queues.join(account('a'),'ranked');expect(queues.searchRange(entry)).toBe(100);now=new Date(9_999);expect(queues.searchRange(entry)).toBe(100);now=new Date(10_000);expect(queues.searchRange(entry)).toBe(150);now=new Date(30_000);expect(queues.searchRange(entry)).toBe(250);});
  it('creates six digit guest rooms and supports join ready start leave',async()=>{const repo=new MemoryRepository(),rooms=new RoomService(repo);const created=await rooms.create(guest('g1'));expect(created.inviteCode).toMatch(/^\d{6}$/);await rooms.join(guest('g2'),created.inviteCode);await rooms.ready(created.id,'g1',true);await rooms.ready(created.id,'g2',true);const started=await rooms.start(created.id,'g1');expect(started.mode).toBe('room');expect((await repo.getActivity('g1'))?.kind).toBe('match');const other=await rooms.create(guest('g3'));await rooms.leave(other.id,'g3');expect(await repo.getActivity('g3')).toBeNull();});
  it('matches only after both rating windows include the opponent',async()=>{let now=new Date(0);const repo=new MemoryRepository(),queues=new QueueService(repo,()=>now);const a=await queues.join(account('a'),'ranked'),b=await queues.join(account('b'),'ranked');a.rating=1000;b.rating=1200;await repo.saveQueue(a);await repo.saveQueue(b);expect(await queues.match('ranked')).toBeNull();now=new Date(20_000);expect(await queues.match('ranked')).not.toBeNull();});
  it('uses a 15 second ready-check deadline and persists proposal state',async()=>{let now=new Date(0);const repo=new MemoryRepository(),queues=new QueueService(repo,()=>now);await queues.join(guest('g1'),'casual');await queues.join(guest('g2'),'casual');const check=await queues.match('casual');expect(check!.deadline.getTime()).toBe(15_000);expect(await repo.getProposal(check!.matchId)).toMatchObject({version:1});now=new Date(14_999);await expect(queues.accept(check!.matchId,'g1')).resolves.toBeDefined();expect((await repo.getProposal(check!.matchId))!.accepted).toEqual(['g1']);});
  it('restores a persisted proposal after service restart',async()=>{let now=new Date(0);const repo=new MemoryRepository(),first=new QueueService(repo,()=>now);await first.join(guest('g1'),'casual');await first.join(guest('g2'),'casual');const check=await first.match('casual');const restarted=new QueueService(repo,()=>now);expect(await restarted.current('g1')).toMatchObject({status:'ready_check',matchId:check!.matchId});await expect(restarted.accept(check!.matchId,'g1')).resolves.toMatchObject({accepted:true});});
  it('exposes a ready check to both real players and starts only after both accept',async()=>{const repo=new MemoryRepository(),queues=new QueueService(repo);await queues.join(guest('g1'),'casual');await queues.join(guest('g2'),'casual');const check=await queues.match('casual');expect(check).not.toBeNull();expect(await queues.current('g1')).toMatchObject({status:'ready_check',matchId:check!.matchId,accepted:false});const first=await queues.accept(check!.matchId,'g1');expect(first).toMatchObject({status:'ready_check',accepted:true});expect(await repo.getMatch(check!.matchId)).toBeNull();const second=await queues.accept(check!.matchId,'g2');expect(second).toMatchObject({status:'playing',matchId:check!.matchId});expect((await repo.getMatch(check!.matchId))?.participants.map(item=>item.principal.id).sort()).toEqual(['g1','g2']);});
  it('creates a rematch for a finished match and preserves both participants',async()=>{const repo=new MemoryRepository(),queues=new QueueService(repo),previous=match();previous.status='finished';previous.result={matchId:previous.id,outcome:'ct',reason:'base',finishedAt:new Date().toISOString(),playerBase:0,aiBase:10};await repo.saveMatch(previous);await repo.claimActivity({principalId:'a',kind:'match',referenceId:previous.id});await repo.claimActivity({principalId:'b',kind:'match',referenceId:previous.id});const next=await queues.rematch(previous.id,'a');expect(next.id).not.toBe(previous.id);expect(next.participants.map(item=>item.principal.id).sort()).toEqual(['a','b']);expect(next.status).toBe('playing');});
  it('creates a single-player PVE room with an AI participant without an AI activity lock',async()=>{const repo=new MemoryRepository(),rooms=new RoomService(repo);const created=await rooms.create(guest('pve'),'PVE');const match=await rooms.start(created.id,'pve');expect(match.participants.map(item=>item.principal.username)).toContain('训练 AI');expect(await repo.getActivity('pve')).toMatchObject({kind:'match'});expect(await repo.getActivity(`${created.id}:ai`)).toBeNull();});
  it('normalizes chat and rejects empty messages',async()=>{const repo=new MemoryRepository(),rooms=new RoomService(repo);const created=await rooms.create(guest('chat-host'));const messages=await rooms.chat(created.id,'chat-host','  hello\nworld\u0000  ');expect(messages.at(-1)?.text).toBe('hello world');await expect(rooms.chat(created.id,'chat-host',' \u0000 ')).rejects.toMatchObject({code:'INVALID_CHAT'});});
  it('lets a second browser join a server room by code and observe the started match',async()=>{const repo=new MemoryRepository(),rooms=new RoomService(repo);const created=await rooms.create(guest('host'));const joined=await rooms.join(guest('visitor'),created.inviteCode);expect(joined.members.map(member=>member.principal.id)).toEqual(['host','visitor']);await rooms.ready(created.id,'visitor',true);const started=await rooms.start(created.id,'host');expect(await rooms.status(created.id,'visitor')).toMatchObject({match:{matchId:started.id}});});
});

describe('private projections',()=>{
  it('only exposes the subscriber shop and private economy',()=>{const runtime=new MatchRuntime(match(),new MemoryRepository());const player=runtime.projection('a');const opponent=runtime.projection('b');expect(player.shops.player).toHaveLength(5);expect(player.shops.ai).toHaveLength(0);expect(player.state.aiMoney).toBe(0);expect(opponent.shops.ai).toHaveLength(5);expect(opponent.shops.player).toHaveLength(0);expect(opponent.state.playerMoney).toBe(0);});
});

describe('ranked settlement',()=>{
  it('settles both ratings once and keeps casual unchanged',async()=>{const repo=new MemoryRepository();const first=await repo.settleRanked('ranked-1','a',['a','b'],'season-v1');const second=await repo.settleRanked('ranked-1','a',['a','b'],'season-v1');expect(first).toEqual(second);expect(await repo.getRating('a','season-v1')).toMatchObject({wins:1});expect(await repo.getRating('b','season-v1')).toMatchObject({losses:1});expect((await repo.getRating('a','season-v1')).elo).not.toBe(1000);expect((await repo.getRating('b','season-v1')).elo).not.toBe(1000);expect(await repo.getRating('c','season-v1')).toMatchObject({elo:1000,wins:0,losses:0,draws:0});});
  it('settles a ranked runtime result idempotently for both accounts',async()=>{const repo=new MemoryRepository(),clock=new FakeClock(),record=match('ranked');await repo.saveMatch(record);const runtime=new MatchRuntime(record,repo,clock);runtime.connect('a');runtime.connect('b');await runtime.command(account('a'),'give-up',{type:'forfeit'});expect(await repo.getRating('a','season-v1')).toMatchObject({losses:1});expect(await repo.getRating('b','season-v1')).toMatchObject({wins:1});const firstRating=await repo.getRating('a','season-v1');const settlements=await repo.settleRanked(record.id,'b',['a','b'],'season-v1');expect(settlements).toHaveLength(2);expect(await repo.getRating('a','season-v1')).toMatchObject({losses:1});expect((await repo.getRating('a','season-v1')).elo).toBe(firstRating.elo);});
});
