import type { CareerState, Decision, DecisionOption, ProbabilityOutcome, Role } from './careerEngine';

export type EventCategory =
  | '赛事内关键局' | '赛事内非关键突发' | '训练状态' | '伤病健康' | '队内体系'
  | '教练管理' | '合同转会' | '角色转职' | '舆论媒体' | '商业赞助'
  | '合规风险' | '家庭生活' | 'CN生态' | '救赎线' | '退役转型';

export interface CareerEventDefinition extends Omit<Decision, 'id'> {
  catalogId: string;
  category: EventCategory;
  minAge?: number;
  maxAge?: number;
  roles?: Role[];
  requiresHiddenFlag?: string;
}

type Scenario = { title: string; scene: string };
type CategoryConfig = {
  kind: CareerEventDefinition['kind'];
  timing?: CareerEventDefinition['timing'];
  minAge?: number;
  maxAge?: number;
  roles?: Role[];
  requiresHiddenFlag?: string;
  optionA: string;
  optionB: string;
  a: [ProbabilityOutcome, ProbabilityOutcome];
  b: [ProbabilityOutcome, ProbabilityOutcome];
};

const visible = (id: string, label: string, probability: number, changes: ProbabilityOutcome['changes'], resultPatch?: ProbabilityOutcome['resultPatch']): ProbabilityOutcome => ({ id, label, probability, changes, resultPatch });
const hidden = (id: string, label: string, probability: number, changes: ProbabilityOutcome['changes'], tag: string, riskHint: string, revealText: string): ProbabilityOutcome => ({
  id, label, probability, changes: {},
  delayed: { tag, riskHint, minSeasons: 1, maxSeasons: 6, changes, revealText },
});

const scenarios: Record<EventCategory, Scenario[]> = {
  '赛事内关键局': [
    {title:'决赛A点回防',scene:'决胜图14:14，你从B区赶回A区，队友只报出一名敌人的位置。'},
    {title:'半决赛残局拆包',scene:'C4只剩十秒，你没有拆包钳，烟雾外可能有人架枪。'},
    {title:'加时赛最后道具',scene:'全队只剩一颗烟和一颗闪，指挥让你决定最后的道具顺序。'},
    {title:'Major生死局保枪',scene:'经济濒临崩溃，你面对几乎不可能完成的1v3。'},
    {title:'决赛第二狙选择',scene:'对手连续针对主狙，你有机会临时起第二把狙改变防守。'},
    {title:'赛点残局假拆',scene:'你听见近点脚步，假拆可能骗出对手，也可能耗尽时间。'},
    {title:'落后一分的强起',scene:'比分11:12，下一局输掉就进入赛点，队伍经济只够半甲道具。'},
    {title:'决胜图临时换点',scene:'对手已经读懂默认，暂停只剩二十秒，教练提出临时换进攻点。'},
    {title:'淘汰局双架取舍',scene:'你和队友可以继续双架，也可以提前散开防止对手绕后。'},
    {title:'决赛残局静步时机',scene:'你知道对手大概率在转点，但不知道他是否已经听见脚步。'},
    {title:'关键局掉包位置',scene:'C4掉在交叉火力中央，强捡包可能直接结束比赛。'},
    {title:'Major加时暂停',scene:'技术暂停后手感中断，队伍需要决定第一局是否主动提速。'},
    {title:'半决赛最后一颗闪',scene:'队友准备干拉，你可以把闪留给自己或帮助他完成突破。'},
    {title:'决赛残局封烟',scene:'你只能封住一个枪位，另一个方向必须依赖队友判断。'},
    {title:'赛点前压侦查',scene:'对手连续慢打，你可以冒险前压获取信息。'},
    {title:'决胜局换枪',scene:'地上有一把子弹更足但不熟悉的武器，时间不允许犹豫。'},
    {title:'保级战残局沟通',scene:'语音里出现两个相反报点，你必须立刻选择相信谁。'},
    {title:'决赛残局追杀',scene:'回合已经拿下，追杀能破坏对手经济，也可能送掉自己的主武器。'},
    {title:'淘汰赛开局路线',scene:'对手已连续两次首杀你，第三次交锋决定你是否改变路线。'},
    {title:'冠军点最后指令',scene:'教练暂停用完，主指挥只来得及给出一个模糊的执行口令。'},
  ],
  '赛事内非关键突发': [
    {title:'比赛鼠标双击',scene:'比赛中段鼠标出现偶发双击，技术暂停次数有限。'},
    {title:'耳机单侧失声',scene:'右侧耳机突然没有声音，裁判正在确认是否允许更换。'},
    {title:'显示器色温异常',scene:'场馆显示器颜色明显偏黄，但所有选手设备统一。'},
    {title:'座椅高度故障',scene:'座椅气压杆不断下沉，下一张地图很快开始。'},
    {title:'队友临时胃痛',scene:'队友突然胃痛，替补已经在后台热身。'},
    {title:'服务器回滚争议',scene:'关键击杀后服务器崩溃，裁判准备回滚整个回合。'},
    {title:'赛场噪声干扰',scene:'隔壁舞台的欢呼声盖过了部分脚步和交流。'},
    {title:'外设驱动重置',scene:'赛前更新重置了灵敏度配置，备份文件需要时间恢复。'},
    {title:'暖手设备失效',scene:'场馆温度很低，你的暖手设备突然停止工作。'},
    {title:'对手请求重赛',scene:'对手声称遭遇丢包，要求重赛上一回合。'},
    {title:'裁判警告交流',scene:'裁判认为你们在暂停期间交流超出规则范围。'},
    {title:'赛前交通延误',scene:'大巴晚到，热身时间只剩原计划的一半。'},
    {title:'训练室临时关闭',scene:'消防检查占用了唯一训练室，赛前准备被打乱。'},
    {title:'地图配置错误',scene:'服务器加载了错误的练习配置，赛事方需要重新开服。'},
    {title:'对手迟到判罚',scene:'对手迟到，裁判询问你们是否接受直接判一图胜。'},
    {title:'队友键盘损坏',scene:'队友备用键盘与你的型号相同，他请求借用你的备用设备。'},
    {title:'观众泄露信息',scene:'观众反应可能泄露绕后信息，裁判要求双方继续比赛。'},
    {title:'赛后药检通知',scene:'比赛刚结束，赛事方临时抽中你参加药检。'},
    {title:'比赛语音设备串线',scene:'比赛语音中出现短暂串线，裁判需要判断是否暂停检查。'},
    {title:'比赛录像丢失',scene:'赛事方告知首图录像损坏，赛后申诉可能缺少证据。'},
  ],
  '训练状态': [
    {title:'首杀专项周',scene:'教练安排一周首杀路线专项训练，但会压缩团队道具时间。'},
    {title:'残局服务器加练',scene:'你获得一套高质量残局训练方案，但每天需要额外两小时。'},
    {title:'反应训练瓶颈',scene:'反应训练成绩停滞，私人教练建议彻底更换训练方法。'},
    {title:'新版本道具课',scene:'版本更新改变了多张地图的道具点位。'},
    {title:'训练赛连续被虐',scene:'队伍连续三天在训练赛中被一线队压制。'},
    {title:'个人教练邀约',scene:'一名数据教练提出短期合作，但费用不低。'},
    {title:'休赛期体能营',scene:'俱乐部安排体能营，与个人枪法集训时间冲突。'},
    {title:'新地图池适应',scene:'新地图进入比赛池，你在这张图的位置经验很少。'},
    {title:'训练量统计争议',scene:'数据组认为你的有效训练量低于队内平均。'},
    {title:'凌晨排位邀请',scene:'顶尖选手邀请你参加高质量深夜排位。'},
    {title:'准星设置实验',scene:'分析师认为新准星可能改善远距离对枪。'},
    {title:'左手持枪尝试',scene:'教练提出短期尝试另一种持枪视角。'},
    {title:'战术手册背诵',scene:'队伍扩充战术手册，要求每人投入额外复盘时间。'},
    {title:'机器人练习替代',scene:'个人教练建议减少排位，改用结构化机器人训练。'},
    {title:'低强度恢复周',scene:'队医建议全队降低训练量，但下一项赛事很重要。'},
    {title:'训练赛换位实验',scene:'教练想在训练赛中让你尝试陌生进攻位置。'},
    {title:'录像自我复盘',scene:'你发现自己的决策问题比枪法问题更明显。'},
    {title:'海外陪练机会',scene:'欧洲队愿意开放一周高质量训练赛名额。'},
    {title:'青训对抗赛',scene:'教练安排主队与青训对抗，年轻人打得异常凶。'},
    {title:'赛前减量争论',scene:'数据组和体能师对赛前训练量给出相反建议。'},
  ],
  '伤病健康': [
    {title:'手腕隐痛',scene:'连续比赛后手腕出现隐痛，影像检查尚未发现结构损伤。'},
    {title:'腰背僵硬',scene:'长途飞行后腰背僵硬，下一项赛事三天后开始。'},
    {title:'睡眠周期紊乱',scene:'连续跨时区比赛让你的睡眠严重紊乱。'},
    {title:'视疲劳加重',scene:'训练后出现短暂视线模糊，医生建议减少屏幕时间。'},
    {title:'颈部旧伤复发',scene:'旧伤在训练赛后复发，但仍可带痛比赛。'},
    {title:'肠胃炎前兆',scene:'队内多人出现肠胃不适，你也开始低烧。'},
    {title:'止痛方案选择',scene:'医生提供保守理疗和短期止痛两套方案。'},
    {title:'体检指标异常',scene:'年度体检发现一项指标异常，需要进一步复查。'},
    {title:'焦虑影响呼吸',scene:'大赛前你开始出现呼吸急促和手心出汗。'},
    {title:'恢复设备试用',scene:'赞助商提供未经长期验证的新恢复设备。'},
    {title:'训练后手指麻木',scene:'高强度训练后无名指出现短暂麻木。'},
    {title:'流感赛季',scene:'队伍所在城市进入流感高发期。'},
    {title:'膝盖运动损伤',scene:'体能训练中膝盖扭伤，不影响坐姿但影响日常恢复。'},
    {title:'咖啡因依赖',scene:'你需要越来越多咖啡因才能保持训练状态。'},
    {title:'噪声性耳鸣',scene:'演出活动后出现轻微耳鸣，比赛交流可能受影响。'},
    {title:'牙科急诊',scene:'海外赛事期间智齿突然发炎。'},
    {title:'心理咨询续约',scene:'心理咨询有效，但长期费用和时间投入不低。'},
    {title:'体脂管理计划',scene:'体能师要求严格饮食，可能影响休赛期生活。'},
    {title:'恢复日被商务占用',scene:'原定恢复日被临时商业活动占用。'},
    {title:'队医建议休赛',scene:'队医认为继续参赛会显著增加长期伤病风险。'},
  ],
  '队内体系': [
    {title:'默认回合分工',scene:'新默认体系要求你牺牲更多个人空间。'},
    {title:'防区搭档更换',scene:'你的固定防区搭档被替换，沟通习惯需要重建。'},
    {title:'资源向主核倾斜',scene:'教练决定把更多道具和经济资源交给队内主核。'},
    {title:'双核体系试验',scene:'队伍准备从单核改为双核体系。'},
    {title:'慢节奏体系转型',scene:'队伍决定降低回合节奏，减少个人即兴。'},
    {title:'进攻端自由度',scene:'教练考虑给你更多中期自由判断权。'},
    {title:'防守轮转重排',scene:'地图更新后全队轮转路线需要重排。'},
    {title:'经济分配冲突',scene:'队伍需要确定谁在经济不足时优先拿长枪。'},
    {title:'首杀职责调整',scene:'教练希望你减少首杀尝试，改为第二身位补枪。'},
    {title:'残局沟通规范',scene:'残局中多人报指令的问题反复出现。'},
    {title:'新人融入体系',scene:'新队友枪法出色但对现有体系理解不足。'},
    {title:'地图永久禁选',scene:'队伍考虑永久放弃你数据最好的地图。'},
    {title:'明星位轮换',scene:'两个选手都希望获得同一个明星位置。'},
    {title:'辅助资源压缩',scene:'新战术会进一步压缩辅助位的经济和数据。'},
    {title:'主动信息权限',scene:'教练考虑让你在防守端主动获取更多信息。'},
    {title:'中期指令简化',scene:'复杂口令导致执行延迟，分析师建议简化体系。'},
    {title:'主客场打法',scene:'队伍在主场和客场的状态差异越来越明显。'},
    {title:'新人替补轮换',scene:'管理层希望在非关键赛事给新人更多地图。'},
    {title:'体系公开风险',scene:'近期比赛录像让对手逐渐摸清队伍习惯。'},
    {title:'赛季末体系坚持',scene:'连败后是否继续坚持现有体系成为核心问题。'},
  ],
  '教练管理': [
    {title:'教练续约评估',scene:'主教练合同即将到期，管理层征询核心选手意见。'},
    {title:'分析师晋升',scene:'年轻分析师希望获得更多战术决策权。'},
    {title:'体能教练预算',scene:'俱乐部只能保留体能教练或第二分析师之一。'},
    {title:'教练暂停风格',scene:'教练的暂停方式被队员认为过于强硬。'},
    {title:'新教练试训',scene:'管理层安排一名候选教练跟队两周。'},
    {title:'赛后批评尺度',scene:'教练在公开采访中直接批评了队伍执行。'},
    {title:'副教练接管',scene:'主教练因个人原因缺席下一项赛事。'},
    {title:'数据组权限',scene:'教练希望限制数据组直接向选手反馈。'},
    {title:'训练迟到处罚',scene:'教练准备对一名多次迟到的主力重罚。'},
    {title:'年轻教练权威',scene:'新教练年龄与你接近，部分老队员不服管理。'},
    {title:'教练与经理分歧',scene:'教练要保留阵容，经理更倾向立即换人。'},
    {title:'复盘会议缩短',scene:'选手普遍疲劳，教练考虑缩短每日复盘。'},
    {title:'私人谈话邀请',scene:'教练希望与你单独讨论队内定位。'},
    {title:'教练临场失误',scene:'一次暂停口令错误直接葬送了关键回合。'},
    {title:'管理层越权',scene:'俱乐部高层开始直接干预首发名单。'},
    {title:'心理教练引入',scene:'主教练希望引入长期心理教练。'},
    {title:'训练纪律升级',scene:'连败后教练提出更严格的作息和训练纪律。'},
    {title:'赛季目标重订',scene:'原定争冠目标已经不现实，教练提出降低目标。'},
    {title:'副指挥任命',scene:'教练准备任命一名副指挥分担中期信息。'},
    {title:'教练下课风声',scene:'媒体提前曝光主教练可能在赛季后离任。'},
  ],
  '合同转会': [
    {title:'合同年涨薪谈判',scene:'合同只剩半年，你的经纪人建议提前谈涨薪。'},
    {title:'强队替补报价',scene:'一线队提供替补合同，训练环境顶级但出场不保证。'},
    {title:'弱队核心合同',scene:'二线队愿意围绕你建队并提供核心待遇。'},
    {title:'买断费僵局',scene:'新队愿意签你，但两家俱乐部在买断费上僵持。'},
    {title:'短约试训邀请',scene:'国际阵容只愿提供三个月试训短约。'},
    {title:'老东家回购',scene:'曾经效力的战队提出回购，但阵容上限有限。'},
    {title:'降薪争冠机会',scene:'争冠队要求你接受明显降薪。'},
    {title:'高薪长约陷阱',scene:'一份三年高薪合同包含严格替补和商务条款。'},
    {title:'自由人窗口',scene:'合同即将结束，你可以提前放弃部分工资换取自由身。'},
    {title:'三人核心报价',scene:'新俱乐部希望整体买下你和两名队友。'},
    {title:'跨赛区报价',scene:'海外队给出正式报价，但语言和签证存在风险。'},
    {title:'首发承诺谈判',scene:'报价薪资不错，却没有明确首发承诺。'},
    {title:'解约金调整',scene:'俱乐部愿意涨薪，条件是大幅提高解约金。'},
    {title:'肖像权条款',scene:'新合同要求俱乐部独占个人肖像权。'},
    {title:'奖金分成重谈',scene:'队伍希望降低固定工资，提高赛事奖金比例。'},
    {title:'替补外租方案',scene:'俱乐部准备把你外租到二线队保持比赛状态。'},
    {title:'经纪人更换',scene:'另一名经纪人承诺带来更好的国际报价。'},
    {title:'合同泄露',scene:'你的薪资条款被匿名账号曝光。'},
    {title:'窗口最后报价',scene:'转会窗关闭前出现一份条件不完整的紧急报价。'},
    {title:'续约附带转型',scene:'俱乐部愿意续约，但要求你接受新的团队定位。'},
  ],
  '角色转职': [
    {title:'副指挥培养计划',scene:'教练邀请你分担赛前准备和少量中期指令。'},
    {title:'原指挥离队接班',scene:'原指挥确认离队，管理层需要在队内寻找接班人。'},
    {title:'教练要求换指挥',scene:'连续失利后，管理层决定更换主指挥。'},
    {title:'赛中临时接管',scene:'主指挥状态崩溃，教练请你临时接管一张地图。'},
    {title:'转狙预备训练',scene:'队伍可能在下赛季失去主狙，教练安排你尝试大狙。'},
    {title:'主狙离队空缺',scene:'主狙正式离队，队伍需要内部转型或外部引援。'},
    {title:'辅助位求生',scene:'年龄和数据下滑后，教练建议你承担更多辅助职责。'},
    {title:'突破位转第二身位',scene:'身体状态下降，继续第一身位的风险越来越高。'},
    {title:'自由人职责尝试',scene:'教练希望你尝试更依赖读图的自由人职责。'},
    {title:'指挥狙实验',scene:'阵容缺少指挥和主狙，管理层提出高风险双重职责。'},
    {title:'枪男指挥路线',scene:'你仍有不错枪法，教练希望保留输出同时学习指挥。'},
    {title:'大脑指挥路线',scene:'数据组认可你的读局，但转型会显著牺牲个人数据。'},
    {title:'成熟体系指挥邀约',scene:'一支成熟强队需要新指挥接手现有体系，但不会直接赋予王朝地位。'}, 
    {title:'临场指挥考核',scene:'教练安排你在训练赛中独立指挥一张地图。'},
    {title:'辅助转指挥铺垫',scene:'长期辅助经验让你熟悉全队道具和节奏。'},
    {title:'狙击手转步枪',scene:'反应和手感波动让主狙位置开始不稳定。'},
    {title:'指挥卸任专注枪法',scene:'长期指挥压力影响健康，你考虑放下指挥权。'},
    {title:'替补期间学指挥',scene:'暂时失去首发后，你有时间系统学习战术。'},
    {title:'残局副指挥职责',scene:'教练只希望你负责残局阶段，不改变主指挥权。'},
    {title:'阵容重组定位重选',scene:'阵容只保留两人，所有位置都要重新确定。'},
  ],
  '舆论媒体': [
    {title:'赛后采访断章取义',scene:'你的回答被剪成十秒短视频并迅速传播。'},
    {title:'TOP榜争议',scene:'媒体认为你的年度排名被高估。'},
    {title:'直播评价队友',scene:'直播中观众不断追问你对一名队友的看法。'},
    {title:'社媒旧言论',scene:'多年前的旧动态被重新翻出。'},
    {title:'输赛后热搜',scene:'关键失误让你的名字登上热搜。'},
    {title:'赛前垃圾话邀请',scene:'赛事方希望你配合制作带火药味的宣传片。'},
    {title:'纪录片拍摄',scene:'媒体希望全程跟拍队伍备战。'},
    {title:'匿名爆料',scene:'匿名账号发布关于队内矛盾的爆料。'},
    {title:'同行公开称赞',scene:'顶尖选手在采访中公开称赞你的发挥。'},
    {title:'数据刷子质疑',scene:'社区认为你的高Rating来自低级赛事。'},
    {title:'粉丝冲突升级',scene:'你的粉丝与队友粉丝在社媒上持续争吵。'},
    {title:'翻译失误',scene:'海外采访翻译改变了你原话的语气。'},
    {title:'失利道歉稿',scene:'俱乐部公关准备了一份标准道歉稿。'},
    {title:'播客长访谈',scene:'知名播客邀请你谈论队内体系和职业压力。'},
    {title:'年度新人标签',scene:'媒体提前把你列为年度新人热门。'},
    {title:'退役传闻',scene:'年龄增长后，媒体开始传播你即将退役的消息。'},
    {title:'转会流言',scene:'媒体曝光你与另一支队伍接触。'},
    {title:'争议庆祝动作',scene:'赛后庆祝动作被部分观众认为不尊重对手。'},
    {title:'直播平台封面',scene:'平台愿意把你放上首页，但要求更高直播时长。'},
    {title:'关键局回放热传',scene:'你的关键回合在社媒上爆火，同时也引来逐帧挑错。'},
  ],
  '商业赞助': [
    {title:'鼠标品牌独家约',scene:'外设品牌提供独家合同，要求更换当前鼠标。'},
    {title:'显示器广告拍摄',scene:'广告拍摄与赛前恢复日冲突。'},
    {title:'签名贴纸分成',scene:'经纪人提出更激进的贴纸分成谈判。'},
    {title:'能量饮料代言',scene:'高额代言与健康形象存在冲突。'},
    {title:'直播平台竞价',scene:'两家平台给出收入和时长完全不同的方案。'},
    {title:'战队周边分成',scene:'俱乐部希望使用你的名字推出个人周边。'},
    {title:'商业赛邀请',scene:'一场高额商业表演赛与训练计划冲突。'},
    {title:'品牌海外活动',scene:'赞助商邀请你跨洲参加发布会。'},
    {title:'低质外设代言',scene:'小品牌报价极高，但产品口碑很差。'},
    {title:'个人品牌计划',scene:'团队建议你投入资金创立个人服装品牌。'},
    {title:'游戏陪玩推广',scene:'平台希望你推广与竞技形象不完全相符的业务。'},
    {title:'签名鼠标开发',scene:'联名产品需要你投入大量测试时间。'},
    {title:'短视频合约',scene:'内容公司保证流量，但要求频繁拍摄。'},
    {title:'赞助冲突审查',scene:'个人赞助与战队主赞助存在品类冲突。'},
    {title:'慈善表演赛',scene:'慈善活动提升形象，但占用唯一休息周末。'},
    {title:'赛事解说客串',scene:'赛事方邀请你在淘汰后客串解说。'},
    {title:'高端品牌形象约',scene:'品牌重视形象，却设置严格言论条款。'},
    {title:'海外粉丝活动',scene:'海外活动有助国际名气，但旅途很长。'},
    {title:'赞助续约压价',scene:'成绩下滑后赞助商提出降价续约。'},
    {title:'冠军奖金广告',scene:'品牌愿意为夺冠设置巨额额外奖金，但会增加压力。'},
  ],
  '合规风险': [
    {title:'灰色顾问费',scene:'品牌提出不经过俱乐部合同的顾问费。'},
    {title:'可疑训练赛',scene:'熟人安排一场奖金来源不明的训练赛。'},
    {title:'盘口群邀请',scene:'旧友邀请你进入一个讨论比赛盘口的群。'},
    {title:'税务补充材料',scene:'税务部门要求补充多年前的收入材料。'},
    {title:'账号共享记录',scene:'平台发现账号曾在异地设备登录。'},
    {title:'外设配置审查',scene:'赛事方对你的外设宏配置提出疑问。'},
    {title:'私下奖金',scene:'俱乐部老板准备以现金发放未写入合同的奖金。'},
    {title:'保密协议冲突',scene:'采访问题涉及合同保密内容。'},
    {title:'礼物申报',scene:'赞助商送来价值很高的个人礼物。'},
    {title:'比赛录像泄露',scene:'你的私人聊天中出现未公开训练录像。'},
    {title:'代言资质问题',scene:'合作品牌被曝缺少必要经营资质。'},
    {title:'经纪人账目异常',scene:'经纪团队账目中出现无法解释的支出。'},
    {title:'反兴奋剂申报',scene:'常用药物需要提前向赛事方申报。'},
    {title:'队友涉嫌假赛',scene:'调查机构联系你了解一名旧队友。'},
    {title:'未成年人合同旧账',scene:'早期青训合同被质疑程序不完整。'},
    {title:'版权音乐直播',scene:'直播平台收到多次版权投诉。'},
    {title:'签证材料真实性',scene:'签证中介建议使用难以核实的补充材料。'},
    {title:'数据隐私授权',scene:'赞助商要求长期收集你的训练和健康数据。'},
    {title:'俱乐部欠税',scene:'俱乐部税务问题可能牵连选手奖金。'},
    {title:'主动合规自查',scene:'律师建议在转会前主动清理历史风险。'},
  ],
  '家庭生活': [
    {title:'家人希望完成学业',scene:'家人希望你保留学习时间，避免职业失败后没有退路。'},
    {title:'长期异地关系',scene:'频繁出国让亲密关系承受压力。'},
    {title:'家庭搬迁决定',scene:'家人考虑搬到俱乐部所在城市支持你。'},
    {title:'父母健康检查',scene:'家人需要陪同检查，但时间与集训冲突。'},
    {title:'朋友借款请求',scene:'早年朋友向你提出一笔不小的借款。'},
    {title:'购房计划',scene:'收入开始稳定，经纪人建议提前购房。'},
    {title:'家庭公开露面',scene:'纪录片团队希望采访你的家人。'},
    {title:'节日无法回家',scene:'海外赛事让你连续第二年无法回家过节。'},
    {title:'亲友管理社媒',scene:'亲友希望帮助管理粉丝社群和社媒账号。'},
    {title:'弟弟进入青训',scene:'家中年轻成员也想进入职业电竞。'},
    {title:'旧友聚会',scene:'多年未见的朋友组织聚会，正值休赛期训练周。'},
    {title:'家庭财务托管',scene:'家人建议把大部分收入交由共同管理。'},
    {title:'搬离战队基地',scene:'你考虑租房独住改善睡眠。'},
    {title:'个人隐私曝光',scene:'住址信息在粉丝群中流传。'},
    {title:'恋情公开压力',scene:'媒体开始追问你的私人关系。'},
    {title:'家乡活动邀请',scene:'家乡邀请你参加大型电竞活动。'},
    {title:'长期旅行疲劳',scene:'家人认为职业日程已经明显影响你的精神状态。'},
    {title:'理财产品推销',scene:'熟人推荐高收益但不透明的理财产品。'},
    {title:'家庭创业投资',scene:'家人希望你投资一项本地生意。'},
    {title:'职业与陪伴',scene:'重要家庭纪念日与国际赛事撞期。'},
  ],
  'CN生态': [
    {title:'欧洲Bootcamp名额',scene:'赞助预算只够一次欧洲集训。'},
    {title:'签证材料延误',scene:'出国赛事前签证材料迟迟没有完成。'},
    {title:'亚洲训练质量',scene:'本地高质量训练赛对手数量不足。'},
    {title:'国际教练报价',scene:'一名海外教练愿意短期加入，但费用很高。'},
    {title:'中文指挥人才短缺',scene:'转会市场缺少成熟中文指挥。'},
    {title:'青训断层',scene:'俱乐部考虑把预算投向长期青训。'},
    {title:'跨区延迟训练',scene:'与欧洲队远程训练的延迟严重。'},
    {title:'亚洲预选压力',scene:'唯一国际名额让区域预选异常残酷。'},
    {title:'国内舆论期待',scene:'一次国际突破后，舆论把复兴希望压在你身上。'},
    {title:'留洋机会',scene:'欧洲二线队提供试训和语言课程。'},
    {title:'国际分析师合作',scene:'海外分析师愿意远程提供对手资料。'},
    {title:'本地赛事冲突',scene:'国内商业赛与国际预选时间重叠。'},
    {title:'长途飞行恢复',scene:'亚洲队需要比欧洲对手更早开始跨洲旅行。'},
    {title:'赞助预算分配',scene:'预算只能用于Bootcamp或引援之一。'},
    {title:'海外服务器适应',scene:'欧洲服务器节奏与亚洲训练环境差异明显。'},
    {title:'区域冠军责任',scene:'赢下亚洲冠军后，外界期待你们代表整个赛区。'},
    {title:'国际媒体沟通',scene:'缺乏稳定翻译影响国际采访和队伍形象。'},
    {title:'国内核心留队',scene:'海外报价可能拆散最有竞争力的中文核心。'},
    {title:'赛区复兴投资',scene:'多家俱乐部讨论共同投资训练基地。'},
    {title:'Major亚洲区名额',scene:'VRS排名边缘让Major阶段资格充满不确定性。'},
  ],
  '救赎线': [
    {title:'再遇决赛旧敌',scene:'你再次遇到曾因自己失误而输掉决赛的对手。'},
    {title:'向旧队友道歉',scene:'多年前的队内冲突仍影响你的口碑。'},
    {title:'伤愈后的首场大赛',scene:'长期伤病后，你第一次回到大型赛事舞台。'},
    {title:'被下放后的回归',scene:'二线磨练后，一线队重新给你试训机会。'},
    {title:'失言后的公开采访',scene:'曾经的采访争议仍被反复提起。'},
    {title:'合同纠纷和解',scene:'旧俱乐部愿意就长期纠纷进行和解。'},
    {title:'关键局心魔重现',scene:'几乎相同的残局和比分再次出现。'},
    {title:'旧教练重新合作',scene:'曾与你冲突的教练加入了新队伍。'},
    {title:'曾拒绝的队伍',scene:'当年被你拒绝的队伍如今成为争冠队。'},
    {title:'低谷后的主场赛',scene:'家乡观众第一次在你低谷后现场支持你。'},
    {title:'替补生涯翻身',scene:'长期替补后，主力突然缺席关键赛事。'},
    {title:'税务风险补救',scene:'旧账尚未爆发，你有机会主动补正。'},
    {title:'队友信任修复',scene:'被你公开批评过的队友再次与你并肩比赛。'},
    {title:'转职失败重试',scene:'上一次转职失败后，教练给出第二次铺垫机会。'},
    {title:'Major资格再临',scene:'曾在预选最后一场出局，如今又来到同一轮。'},
    {title:'老东家淘汰赛相遇',scene:'离队时关系破裂的老东家成为淘汰赛对手。'},
    {title:'粉丝重新接纳',scene:'长期稳定表现让舆论态度开始变化。'},
    {title:'伤病隐患复查',scene:'早年带伤出战留下的隐患可以彻底治疗。'},
    {title:'错失MVP后的决赛',scene:'上次决赛隐身让你错过MVP，这次机会再次出现。'},
    {title:'职业最后一次冲冠',scene:'年龄和合同状况意味着这可能是最后一次争冠机会。'},
  ],
  '退役转型': [
    {title:'青训教练邀请',scene:'俱乐部邀请你退役后负责青训。'},
    {title:'分析师岗位',scene:'数据团队认为你的比赛理解适合转型分析师。'},
    {title:'解说台试镜',scene:'赛事方邀请你参加解说试镜。'},
    {title:'直播全职合同',scene:'平台提供退役后的长期直播保障。'},
    {title:'战队管理岗位',scene:'老东家希望你进入管理层。'},
    {title:'继续征战二线',scene:'一线合同减少，但二线队仍愿意给首发。'},
    {title:'海外教练机会',scene:'海外俱乐部提供助理教练岗位。'},
    {title:'个人训练营',scene:'你考虑开办面向年轻选手的训练营。'},
    {title:'选手经纪转型',scene:'经纪公司邀请你学习选手管理。'},
    {title:'赛事运营岗位',scene:'虚构赛事方希望你参与赛事设计。'},
    {title:'短暂休赛计划',scene:'你想休息半年再决定是否退役。'},
    {title:'最后一份长约',scene:'一支二线队提供可能覆盖余下生涯的长约。'},
    {title:'国家队顾问',scene:'地区代表队邀请你担任短期顾问。'},
    {title:'内容创作团队',scene:'纪录片团队希望围绕你的生涯制作长期内容。'},
    {title:'俱乐部合伙机会',scene:'小俱乐部邀请你以资金和名气入股。'},
    {title:'校园电竞讲师',scene:'高校项目邀请你担任电竞课程讲师。'},
    {title:'复出条款',scene:'退役合同中可以保留一次短期复出机会。'},
    {title:'告别赛安排',scene:'俱乐部愿意为你组织正式告别赛。'},
    {title:'家庭优先决定',scene:'长期职业生活后，家庭希望你结束频繁旅行。'},
    {title:'无声离开还是公开告别',scene:'你需要决定如何向公众结束职业生涯。'},
  ],
};

const categoryExtras:Record<EventCategory,Scenario>={
  '赛事内关键局':{title:'决赛最后一次战术暂停',scene:'比分来到赛点，最后一次暂停只能解决进攻路线或经济分配中的一个问题。'},
  '赛事内非关键突发':{title:'现场电脑帧数骤降',scene:'比赛中电脑帧数偶发下降，重启可能恢复，也会中断手感。'},
  '训练状态':{title:'赛季中微调灵敏度',scene:'数据教练发现微调灵敏度可能改善近距离对枪，但适应期紧邻大赛。'},
  '伤病健康':{title:'拇指关节劳损',scene:'长期按键习惯导致拇指关节劳损，短期仍能比赛。'},
  '队内体系':{title:'残局资源重新分配',scene:'队伍准备把残局经济和道具优先交给更稳定的选手。'},
  '教练管理':{title:'教练组赛季复盘',scene:'赛季结束后教练组要求每名选手接受匿名队内评价。'},
  '合同转会':{title:'双向选项合同',scene:'新合同允许双方在一年后跳出，灵活性和稳定性都受到影响。'},
  '角色转职':{title:'成熟体系接班考核',scene:'成熟强队把一个月训练营作为主指挥接班考核。王朝地位只能由长期成绩形成。'}, 
  '舆论媒体':{title:'赛后数据图争议',scene:'赛事方发布的数据图遗漏关键上下文，引发排名争论。'},
  '商业赞助':{title:'个人纪录片冠名',scene:'赞助商愿意冠名个人纪录片，但要求介入剪辑方向。'},
  '合规风险':{title:'比赛电脑USB审查',scene:'裁判发现比赛电脑连接记录中存在未备案USB设备。'},
  '家庭生活':{title:'职业基地探访',scene:'家人第一次来到长期封闭管理的战队基地。'},
  'CN生态':{title:'亚洲联合训练营',scene:'多支亚洲队讨论共享训练资源，但彼此担心战术泄露。'},
  '救赎线':{title:'旧伤后的同一场馆',scene:'你回到曾因伤退赛的场馆，身体和记忆同时承受压力。'},
  '退役转型':{title:'选手委员会席位',scene:'赛事体系邀请你退役后加入选手委员会参与规则讨论。'},
};
(Object.keys(categoryExtras) as EventCategory[]).forEach(category=>scenarios[category].push(categoryExtras[category]));

const configs: Record<EventCategory, CategoryConfig> = {
  '赛事内关键局': { kind:'field', timing:'in-season', optionA:'执行高风险处理', optionB:'交给体系和队友', a:[visible('a-hit','判断奏效，回合被你改写',42,{ability:4,fame:6,health:-3},{placementDelta:1}),visible('a-miss','判断失误，但队伍仍可能兜底',58,{ability:-3,connections:-4,highPressureChokingRisk:5},{placementDelta:-1})], b:[visible('b-hold','队友完成后续处理',62,{connections:4,teamForm:3,fame:-1}),visible('b-drop','队友没能兜住',38,{connections:-2,teamForm:-4,ability:-1},{placementDelta:-1})] },
  '赛事内非关键突发': { kind:'field', timing:'in-season', optionA:'立即处理问题', optionB:'维持比赛节奏', a:[visible('a-ok','问题及时处理，但热身被打断',72,{integrity:3,ability:-2}),hidden('a-risk','表面恢复，后续留下隐患',28,{ability:1,health:-2},'injuryRisk','存在长期状态风险','早前赛事中的隐患重新影响了状态。')], b:[visible('b-steady','比赛继续，影响被控制',58,{ability:2,health:-2}),visible('b-cost','问题扩大，状态明显受损',42,{ability:-4,health:-4,connections:2})] },
  '训练状态': { kind:'offseason', optionA:'投入专项训练', optionB:'保留综合训练', a:[visible('a-growth','专项取得突破，但身体负荷上升',55,{ability:5,health:-5}),hidden('a-stall','训练效果有限，并形成错误习惯',45,{ability:1,health:-3},'rolePrep','可能影响后续位置适应','早前形成的训练习惯在新体系中暴露问题。')], b:[visible('b-balance','综合状态更稳定，突破有限',68,{ability:2,health:2,fame:-1}),visible('b-flat','训练缺少重点，进步停滞',32,{ability:-1,health:4,connections:-2})] },
  '伤病健康': { kind:'emergency', optionA:'接受完整治疗', optionB:'控制风险继续参赛', a:[visible('a-heal','恢复顺利，但错过部分训练',78,{health:10,ability:-3,fame:-2}),hidden('a-slow','恢复慢于预期，主力位置受压',22,{health:4,connections:-4},'managementTrust','可能影响后续首发与续约','管理层在评估出勤时重新提起了这段休赛。')], b:[visible('b-survive','身体撑住，队友认可你的投入',57,{health:-6,connections:6,ability:2}),hidden('b-worse','伤势加重并留下长期隐患',43,{health:-12,ability:-3},'injuryRisk','存在长期伤病风险','带伤参赛留下的隐患在高密度赛程中复发。')] },
  '队内体系': { kind:'field', timing:'post-report', optionA:'接受体系调整', optionB:'争取保留个人空间', a:[visible('a-fit','体系运转更顺，但个人数据承压',64,{teamForm:6,connections:4,ability:-2}),visible('a-lost','适应不佳，个人与团队都受影响',36,{teamForm:-3,positionFamiliarity:-6,connections:2})], b:[visible('b-star','个人发挥提升，但短板被放大',48,{ability:5,fame:4,connections:-5}),hidden('b-friction','教练暂时让步，内部评价下降',52,{ability:2,connections:-2},'managementTrust','可能影响未来资源和首发','管理层在新的阵容讨论中降低了对你的信任。')] },
  '教练管理': { kind:'emergency', optionA:'支持教练组方案', optionB:'要求重新讨论', a:[visible('a-order','管理秩序稳定，但部分队友不满',67,{rosterStability:7,connections:-3,integrity:2}),hidden('a-faction','方案通过，却形成队内派系',33,{teamForm:2},'teamFaction','可能影响后续更衣室事件','早前形成的队内派系在连败后公开化。')], b:[visible('b-revise','方案被修正，沟通成本上升',54,{connections:5,teamForm:3,health:-3}),visible('b-authority','讨论失控，教练权威受损',46,{connections:-5,rosterStability:-7,fame:3})] },
  '合同转会': { kind:'offseason', optionA:'接受确定性更高的方案', optionB:'继续谈判更高上限', a:[visible('a-secure','合同落地，但竞技上限受限',70,{earnings:12,connections:4,ability:-2}),hidden('a-clause','合同落地，隐藏条款日后成为束缚',30,{earnings:8},'managementTrust','合同可能影响未来转会与首发','旧合同条款在新的转会窗口中限制了选择。')], b:[visible('b-win','谈判成功，获得更好竞技条件',38,{fame:7,ability:4,connections:-3}),visible('b-collapse','报价撤回，市场评价受损',62,{connections:-8,fame:-4,earnings:-3})] },
  '角色转职': { kind:'offseason', optionA:'接受有铺垫的转型', optionB:'维持当前主职', a:[visible('a-sign','转型初现端倪，但数据进入阵痛',50,{rolePreparation:'igl-assistant',ability:-4,connections:6}),hidden('a-pain','职责完成交接，管理层耐心开始消耗',50,{rolePreparation:'igl-assistant',ability:-7},'rolePrep','可能影响后续转职结果','早期转型的阵痛在位置竞争中被重新评估。')], b:[visible('b-stay','当前数据稳定，转型窗口收窄',66,{ability:2,connections:-2,fame:1}),visible('b-outdated','版本变化让原定位进一步边缘化',34,{ability:-3,positionFamiliarity:-4,health:2})] },
  '舆论媒体': { kind:'field', timing:'post-report', optionA:'主动回应', optionB:'交给俱乐部公关', a:[visible('a-own','回应获得支持，但争议继续升温',46,{fame:9,integrity:3,connections:-4}),hidden('a-backlash','短期热度上升，叙事埋下反噬',54,{fame:6,integrity:-2},'mediaNarrative','可能影响未来采访与舆论','早前形成的媒体叙事在失利后再次反噬。')], b:[visible('b-calm','争议降温，但个人声音减弱',74,{connections:5,fame:-4,integrity:2}),visible('b-cold','标准回应被认为缺乏担当',26,{fame:-5,connections:-2,integrity:1})] },
  '商业赞助': { kind:'offseason', optionA:'接受商业合作', optionB:'优先竞技安排', a:[visible('a-money','合作顺利，但训练时间被压缩',63,{earnings:14,fame:7,ability:-4}),hidden('a-brand','收入到账，品牌风险被暂时掩盖',37,{earnings:10,fame:4},'complianceRisk','存在长期品牌或合规风险','早前合作品牌的问题开始波及个人信誉。')], b:[visible('b-focus','竞技准备改善，商业热度下降',69,{ability:5,health:-2,fame:-4}),visible('b-missed','训练效果一般，也错过合作窗口',31,{ability:1,fame:-5,connections:-3})] },
  '合规风险': { kind:'emergency', optionA:'主动申报并留证', optionB:'通过私人渠道处理', a:[visible('a-clean','程序合规，但付出收入和关系代价',86,{integrity:9,earnings:-8,connections:-3}),hidden('a-paper','材料基本完整，仍有小范围复查风险',14,{integrity:4,earnings:-4},'complianceRisk','仍可能触发后续复查','补充材料中的旧记录再次被调查人员要求解释。')], b:[visible('b-cover','短期顺利解决，信誉略有损失',58,{earnings:8,connections:6,integrity:-6}),hidden('b-investigation','问题被压下，但调查计时器启动',42,{earnings:12,integrity:-12},'complianceRisk','可能在未来触发调查','早前未正式申报的问题进入了调查程序。')] },
  '家庭生活': { kind:'offseason', optionA:'优先处理家庭事务', optionB:'维持职业安排', a:[visible('a-family','家庭关系改善，但训练和收入受损',71,{health:6,ability:-3,earnings:-4}),hidden('a-duty','问题暂时解决，未来仍需投入时间',29,{health:2,connections:2},'familyDuty','可能影响未来赛程或转会','先前搁置的家庭安排再次与赛程发生冲突。')], b:[visible('b-career','竞技状态维持，私人压力增加',62,{ability:4,health:-5,fame:2}),visible('b-break','职业安排完成，但家庭支持下降',38,{ability:2,health:-7,connections:-5})] },
  'CN生态': { kind:'offseason', optionA:'投入国际化资源', optionB:'稳住国内基本盘', a:[visible('a-world','国际适应提升，但成本和疲劳明显',44,{internationalAdaptation:12,ability:4,health:-7,earnings:-6}),hidden('a-culture','训练质量提高，文化磨合风险累积',56,{internationalAdaptation:7,connections:-4},'managementTrust','可能影响后续国际阵容磨合','早前国际化投入带来的文化分歧重新出现。')], b:[visible('b-home','国内默契稳定，国际上限没有突破',73,{connections:7,teamForm:5,internationalAdaptation:-3}),visible('b-stagnate','环境舒适，但版本理解继续落后',27,{connections:4,ability:-4,internationalAdaptation:-5})] },
  '救赎线': { kind:'field', timing:'in-season', requiresHiddenFlag:'mediaNarrative', optionA:'主动面对过去', optionB:'只专注当下比赛', a:[visible('a-redemption','完成救赎，但消耗巨大',43,{ability:7,fame:12,health:-5,highPressureChokingRisk:-12}),hidden('a-haunt','尝试失败，心魔进一步加深',57,{ability:-4,fame:-7,highPressureChokingRisk:12},'trauma','可能影响未来关键局','未完成的救赎在下一次高压比赛前再次出现。')], b:[visible('b-professional','稳定完成比赛，但错过叙事加成',68,{ability:2,connections:3,fame:-2}),visible('b-trigger','旧记忆仍影响关键判断',32,{ability:-2,health:-4,highPressureChokingRisk:5})] },
  '退役转型': { kind:'annual', minAge:27, optionA:'提前铺设转型道路', optionB:'继续押注选手生涯', a:[visible('a-next','下一阶段更稳，但竞技投入下降',76,{connections:9,fame:5,ability:-5}),hidden('a-politics','岗位机会出现，同时卷入管理关系',24,{connections:5,ability:-3},'managementTrust','可能影响未来合同与退役岗位','早前接触的管理岗位在阵容调整中要求你表态。')], b:[visible('b-last-run','状态短暂回升，身体负担加重',39,{ability:7,health:-9,fame:6}),visible('b-decline','继续坚持却没有等到反弹',61,{ability:-5,health:-6,fame:-3})] },
};

const makeOption = (catalogId: string, id: string, label: string, outcomes: [ProbabilityOutcome, ProbabilityOutcome]): DecisionOption => ({
  id: `${catalogId}-${id}`,
  label,
  detail: outcomes.map(outcome => `${outcome.probability}% ${outcome.delayed?'存在长期风险':outcome.label}`).join(' / '),
  changes: {},
  outcomes: outcomes.map(outcome => ({ ...outcome, id: `${catalogId}-${outcome.id}` })),
});

export const CAREER_EVENT_CATALOG: CareerEventDefinition[] = (Object.keys(scenarios) as EventCategory[]).flatMap(category => {
  const config = configs[category];
  return scenarios[category].map((scenario, index) => {
    const catalogId = `${category}-${String(index + 1).padStart(2, '0')}`;
    return {
      catalogId,
      category,
      kind: config.kind,
      timing: config.timing,
      title: scenario.title,
      briefing: scenario.scene,
      minAge: config.minAge,
      maxAge: config.maxAge,
      roles: config.roles,
      requiresHiddenFlag: config.requiresHiddenFlag,
      options: [
        makeOption(catalogId, 'a', config.optionA, config.a),
        makeOption(catalogId, 'b', config.optionB, config.b),
      ],
    };
  });
});

export const eligibleCatalogEvents = (state: CareerState, kind: Decision['kind'], timing?: Decision['timing']) => CAREER_EVENT_CATALOG.filter(event => {
  if (event.kind !== kind) return false;
  if (timing && event.timing && event.timing !== timing) return false;
  if (event.minAge !== undefined && state.age < event.minAge) return false;
  if (event.maxAge !== undefined && state.age > event.maxAge) return false;
  if (event.roles && !event.roles.includes(state.role)) return false;
  if (event.requiresHiddenFlag && !state.hiddenFlags[event.requiresHiddenFlag]) return false;
  if (event.category === 'CN生态' && state.region !== 'Asia') return false;
  return true;
});

export const EVENT_CATALOG_SIZE = CAREER_EVENT_CATALOG.length;
